- generic [ref=e4]:
  - banner [ref=e5]:
    - generic [ref=e6]:
      - generic [ref=e7]:
        - heading "Claude" [level=1] [ref=e8]
        - img [ref=e9]
      - generic [ref=e12]:
        - button "会话管理" [ref=e13] [cursor=pointer]:
          - img [ref=e14]
          - text: 会话管理
        - button "Add provider" [ref=e17] [cursor=pointer]:
          - img [ref=e18]
  - main [ref=e19]:
    - generic [ref=e20]:
      - generic [ref=e22]:
        - generic [ref=e23]:
          - img [ref=e25]
          - generic [ref=e27]:
            - generic [ref=e28]:
              - heading "Anthropic" [level=3] [ref=e29]
              - generic [ref=e30]: Enabled
            - paragraph [ref=e31]: https://api.anthropic.com
        - generic [ref=e32]:
          - button "Enable Anthropic" [ref=e33] [cursor=pointer]:
            - img [ref=e34]
            - text: 启用
          - button "Edit Anthropic" [ref=e36] [cursor=pointer]:
            - img [ref=e37]
          - button "Delete Anthropic" [ref=e40] [cursor=pointer]:
            - img [ref=e41]
      - generic [ref=e45]:
        - generic [ref=e46]:
          - img [ref=e48]
          - generic [ref=e51]:
            - generic [ref=e52]:
              - heading "Zhipu GLM en" [level=3] [ref=e53]
              - generic [ref=e54]: Enabled
            - paragraph [ref=e55]: https://api.z.ai/api/anthropic
        - generic [ref=e56]:
          - button "Enable Zhipu GLM en" [ref=e57] [cursor=pointer]:
            - img [ref=e58]
            - text: 启用
          - button "Edit Zhipu GLM en" [ref=e60] [cursor=pointer]:
            - img [ref=e61]
          - button "Delete Zhipu GLM en" [ref=e64] [cursor=pointer]:
            - img [ref=e65]